site_name: Ansari Documentation
site_url: https://docs.askansari.ai
nav:
  - Home: index.md
  - What Ansari can do: capabilities.md
  - Validation: validation.md
  - FAQ: faq.md
  - Additional material: material.md
  - Privacy policy: privacy.md
  - Terms of service: terms.md
  - Newsletter: newsletter.md
  - Support: support.md

theme: readthedocs

extra_css:
  - css/extra.css

extra_javascript:
  - js/newsletter.js

